### ISSUE TITLE
create_storage_resource function issues

### ISSUE THREAD

**Issue by mattmonday** [open-e/jdss-api-tools#19]
According to documentation, we should be able to specify --target_name arg to issue a target name when creating a resource. Actual arg is --target in the code, so the example in the documentation is wrong.

Example shown:
**jdss-api-tools.exe create_storage_resource --pool Pool-0 --storage_type iscsi --volume zvol00 --target_name iqn.2018-09:ha-00.target0 --size 1TB --provisioning thin --node 192.168.0.220**

What it should be:
**jdss-api-tools.exe create_storage_resource --pool Pool-0 --storage_type iscsi --volume zvol00 --target iqn.2018-09:ha-00.target0 --size 1TB --provisioning thin --node 192.168.0.220**

Next issue is that no matter what you specify as the target name and zvol name in the command, the target name and zvol name revert to the "defaults" and attempts to generate its own target and zvol name.

In the create_Storage_resource() function:

```
generate_automatic_name = (
        True if target_name == 'auto' else False) or (
        True if share_name  == 'auto' else False)
```

These lines set generate_automatic_name to true if either target name or share name is "auto", and both of these variables carry a default value of auto. Therefore, both need to be specified in the command if you don't want to generate an auto target and zvol name. So the example given in the documentation creates the target/zvol with auto generated values ALL the time (unless you also change the share_name arg from its default value of auto). 

As a workaround, you can just specify the share_name parameter in the command as it has no effect since the storage type is "iscsi"

**Comment by januszbak** [comment]
Thank you for the feedback.
The Recent fixes must solve this problem.
